---
name: Tests


on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "*"


jobs:
  tests:
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9", "3.10", "3.11", "3.12"]
        os: [ubuntu-22.04, ubuntu-24.04]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/pip
            ~/.local/share/hatch/env/virtual/
          key: ${{ runner.os }}-${GITHUB_JOB}-${{ hashFiles('pyproject.toml') }}
          restore-keys: |
            ${{ runner.os }}-${GITHUB_JOB}

      - run: |
          python3 -m venv /tmp/venv
          /tmp/venv/bin/python -m pip install --upgrade pip hatch coverage

      - run: /tmp/venv/bin/hatch run testing:cov

      - uses: codecov/codecov-action@v4.0.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: aleph-im/aleph-message
